studentDb/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.views.generic.base import RedirectView, TemplateView
from students.views import students, groups, exams, contact_admin
from students.views.students import StudentUpdateView
from students.views.groups import GroupUpdateView
from students.views.exams import ExamUpdateView
from students.views.journal import JournalView
from studentDb.views import editProfileView
from .settings import DEBUG, MEDIA_ROOT
from django.views.static import serve


js_info_dict = {
  'packages': ('students',),
}
 
urlpatterns = [

    # User Related urls:
    url(r'^users/profile/(?P<pk>\d+)/edit/$', editProfileView.as_view(), name='profile_edit'),
    url(r'^users/profile/$', login_required(TemplateView.as_view(template_name='registration/profile.html')),
      name='profile'),
    url(r'^users/logout/$', auth_views.logout, kwargs={'next_page':'home'},
          name='auth_logout'),
    url(r'^register/complete/$', RedirectView.as_view(pattern_name='home'),
          name='registration_complete'),
    url(r'^users/', include('registration.backends.simple.urls', namespace='users')),
    
    # Students url patterns:
    url(r'^$', students.student_list, name='home'),
  	url(r'^students/add/$', students.students_add, name='students_add'),
   	url(r'^students/(?P<pk>\d+)/edit/$', StudentUpdateView.as_view(), name='students_edit'),
  	url(r'^students/(?P<pk>\d+)/delete/$', students.students_delete, name='students_delete'),

    # Groups url patterns:
    url(r'^groups$', login_required(groups.group_list), name='groups'),
    url(r'^groups/(?P<pk>\d+)/edit/$', login_required(GroupUpdateView.as_view()), name='groups_edit'),
  	url(r'^groups/(?P<pk>\d+)/delete/$', login_required(groups.groups_delete), name='groups_delete'),

  	# Exams url patterns:
  	url(r'^exams$', exams.exams_list, name='exams'),
    url(r'^exams/add/$', exams.exams_add, name='exams_add'),
    url(r'^exams/(?P<pk>\d+)/edit/$', ExamUpdateView.as_view(), name='exams_edit'),
    url(r'^exams/(?P<pk>\d+)/delete/$', exams.exams_delete, name='exams_delete'),

    # Journal url patterns:
    url(r'^journal/(?P<pk>\d+)?/?$', JournalView.as_view(), name='journal'),

    # Contact Admin url:
    url(r'^contact-admin/$', contact_admin.contact_admin, name='contact_admin'),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^jsi18n\.js$', 'django.views.i18n.javascript_catalog', js_info_dict),
]

if DEBUG:
	urlpatterns += [
		url(r'media/(?P<path>.*)$', serve,
	 	{'document_root': MEDIA_ROOT})
	]

students/models.py
# -*- coding: utf-8 -*-

from django.db import models

# Student Model 
class Student(models.Model):

	class Meta(object):
		verbose_name = u'Студент'
		verbose_name_plural = u'Студенти'

	first_name = models.CharField(
		max_length=256,
		blank=False,
		verbose_name=u"Ім'я")

	last_name = models.CharField(
		max_length=256,
		blank=False,
		verbose_name=u'Прізвище')

	middle_name = models.CharField(
		max_length=256,
		blank=True,
		verbose_name=u'По-батькові',
		default='')

	birthday = models.DateField(
		blank=False,
		verbose_name=u'День народження',
		null=True)

	photo = models.ImageField(
		blank=True,
		verbose_name=u'Фото',
		null=True)

	ticket = models.IntegerField(
		max_length=256,
		blank=False,
		verbose_name=u'Білет')

	notes = models.TextField(
		blank=True,
		verbose_name=u'Додаткові нотатки')

	def __unicode__(self):
		return u'%s %s' % (self.first_name, self.last_name)

students/models/exams.py
# -*- coding: utf-8 -*-

from django.db import models

# Exams Model
class Exam(models.Model):

    class Meta(object):
        verbose_name = u'Іспит'
        verbose_name_plural = u'Іспити'

    subject = models.CharField(
    	max_length=256,
    	blank=False,
    	verbose_name=u"Назва предмету")

    dataAndTime = models.DateTimeField(
    	blank=False,
    	verbose_name=u'Дата та час іспиту',
    	null=True)

    teacher = models.CharField(
    	max_length=256,
    	blank=False,
    	null=True,
    	verbose_name=u'Викладач')

    exam_group = models.ForeignKey(
    	'Group',
    	verbose_name=u'Група',
    	blank=False,
    	null=True,
    	on_delete = models.PROTECT)
    

    def __unicode__(self):
       	return u'%s (%s %s)' % (self.subject, self.teacher, self.exam_group)
      

students/models/groups.py
# -*- coding: utf-8 -*-

from django.db import models

# Group Model
class Group(models.Model):

    class Meta(object):
        verbose_name = u'Група'
        verbose_name_plural = u'Групи'

    title = models.CharField(
    	max_length=256,
    	blank=False,
    	verbose_name=u"Назва")

    leader = models.OneToOneField('Student',
    	verbose_name=u'Староста',
    	blank=True,
    	null=True,
    	on_delete=models.SET_NULL)

    notes = models.TextField(
    	blank=True,
    	verbose_name=u'Додаткові нотатки')

    def __unicode__(self):
        if self.leader:
        	return u'%s (%s %s)' % (self.title, self.leader.first_name, self.leader.last_name)
        else:
        	return u'%s' % (self.title)

students/views/contact_admin.py
# -*- coding: utf-8 -*-
import logging

from django.shortcuts import render
from django import forms
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.contrib.auth.decorators import permission_required

from studentDb.settings import ADMIN_EMAIL

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, ButtonHolder


class ContactForm(forms.Form):

	def __init__(self, *args, **kwargs):
		super(ContactForm, self).__init__(*args, **kwargs)

		# this helper object allows us to customize form
		self.helper = FormHelper()

		# form tag attributes
		self.helper.form_class = 'form-horizontal'
		self.helper.form_method = 'post'
		self.helper.form_action = reverse('contact_admin')

		#twitter bootstrap styles
		self.helper.help_text_inline = True
		self.helper.html5_required = True
		self.helper.label_class = 'col-sm-3 control-label'
		self.helper.field_class = 'col-sm-6'

		# form buttons

		self.helper.add_input(Submit('send_button', u'Надіслати'))
		

	from_email = forms.EmailField(
		label=u'Ваша Емейл Адреса')

	subject = forms.CharField(
		label=u'Заголовок листа',
		max_length=128)

	message = forms.CharField(
		label=u'Текст повідомлення',
		max_length=2560,
		widget=forms.Textarea)

@permission_required('auth.add_user')
def contact_admin(request):
	if request.method == 'POST':
		form = ContactForm(request.POST)

		if form.is_valid():
			subject = form.cleaned_data['subject']
			message = form.cleaned_data['message']
			from_email = form.cleaned_data['from_email']

			try:
				send_mail(subject, message, from_email, [ADMIN_EMAIL])
			except Exception:
				message = u'Під час відправки листа виникла помилка'
				messages.warning(request, message)
				logger = logging.getLogger(__name__)
				logger.exception(message)
			else:
				message = u'Повідомлення успішно надіслане!'
				messages.success(request, message)

			return HttpResponseRedirect(reverse('contact_admin'))
	else:
		form = ContactForm()

	return render(request, 'contact_admin/form.html', {'form':form})

students/views/exams.py
# -*- coding: utf-8 -*-

from datetime import datetime

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import UpdateView
from django.forms import ModelForm, ValidationError

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from crispy_forms.bootstrap import FormActions, AppendedText

from ..models.exams import Exam
from ..models.groups import Group

from ..util import paginate, get_current_group

# Exam List View ################################################
def exams_list(request):
	current_group = get_current_group(request)

	if current_group:
		exams = Exam.objects.filter(exam_group=current_group)
	else:
		exams = Exam.objects.all()

	# try to order exams list
	order_by = request.GET.get('order_by', 'subject')
	if order_by in ('subject', 'dataAndTime'):
		exams = exams.order_by(order_by)
		if request.GET.get('reverse', '') == '1':
			exams = exams.reverse()
		
	# paginate of exams list
	context = paginate(exams, 3, request, {'exams':exams}, var_name='exams')


	return render(request, 'students/exams_list.html', context)
#Exam Add Form #########################################################################################
def exams_add(request):
	groups = Group.objects.all().order_by('title')

	# if form was posted
	if request.method =="POST":
		# if form add_button was clicked
		if request.POST.get('add_button') is not None:
			# Validate input data
			errors = {}

			data = {}

			subject = request.POST.get('subject', '').strip()
			if not subject:
				errors['subject'] = u"Предмет є обов'язковим"
			else:
				data['subject'] = subject

			dataAndTime = request.POST.get('dataAndTime', '').strip()
			if not dataAndTime:
				errors['dataAndTime'] = u"Дата та час іспиту є обов'язковими"
			else:
				try:
					datetime.strptime(dataAndTime, '%Y-%m-%d %H:%M')
				except Exception:
					errors['dataAndTime'] = u"Введіть коректний формат дати (Напр. 2016-11-01 14:00)"
				else:
					data['dataAndTime'] = dataAndTime

			teacher = request.POST.get('teacher', '').strip()
			if not teacher:
				errors['teacher'] = u"Прізвище та ініціали викладача обов'язкові"
			else:
				data['teacher'] = teacher

			exam_group = request.POST.get('exam_group', '').strip()
			if not exam_group:
				errors['exam_group'] = u"Оберіть групу для іспиту"
			else:
				groups = Group.objects.filter(pk=exam_group)
				if len(groups) != 1:
					errors['exam_group'] = u"Оберіть коректну групу"
				else:
					data['exam_group'] = groups[0]

			# save exam
			if not errors:
				exam = Exam(**data)
				exam.save()
				#redirect user to students list
				messages.success(request, u'Іспит з предмету "%s" для групи %s успішно доданий' %
					 (exam.subject, exam.exam_group.title))
				return HttpResponseRedirect(reverse('exams') )
			else:
				# render form with errors and previous user input
				return render(request, 'students/exams_add.html',
					{'groups':groups, 'errors':errors})
		
		elif request.POST.get('cancel_button') is not None:
			# redirect to exams page on cancel button
			messages.warning(request, u'Додавання іспиту скасовано!')
			return HttpResponseRedirect(reverse('exams'))
	else:
		# initial form render
		return render(request, 'students/exams_add.html', {'groups':groups})
# Exams Edit View #########################################################################

class ExamUpdateForm(ModelForm):
	class Meta:
		model = Exam
		fields = ['subject', 'dataAndTime', 'teacher', 'exam_group']

	def __init__(self, *args, **kwargs):
		super(ExamUpdateForm, self).__init__(*args, **kwargs)

		self.helper = FormHelper(self)

		# set form tag attributes
		self.helper.form_action = reverse('exams_edit', kwargs = {'pk': kwargs['instance'].id})
		self.helper.form_method = 'post'
		self.helper.form_class = 'form-horizontal'

		# set form field properties
		self.helper.help_text_inline = True
		self.helper.html5_required = True
		self.helper.label_class = 'col-sm-3 control-label'
		self.helper.field_class = 'col-sm-6 input-form'

		# add calendar icon to birthday input field
		self.helper.layout[1] = AppendedText("dataAndTime", '<span class="glyphicon glyphicon-calendar"></span>', active=True)
		# add buttons
		self.helper.add_input(Submit('add_button', u'Зберегти', css_class="btn btn-primary"))
		self.helper.add_input(Submit('cancel_button', u'Скасувати', css_class="btn btn-link"))

class ExamUpdateView(SuccessMessageMixin, UpdateView):
	model = Exam
	template_name = 'students/exams_edit.html'
	form_class = ExamUpdateForm
	success_message = u"Іспит з '%(calc_last_name)s' успішно збережений"

	def get_success_url(self):
		return reverse('exams')

	def get_success_message(self, cleaned_data):
		return self.success_message % dict(cleaned_data, calc_last_name=self.object.subject,)

	def post(self, request, *args, **kwargs):
		if request.POST.get('cancel_button'):
			messages.warning(request, u'Редагування іспиту з "%s" скасовано!' % request.POST['subject'])
			return HttpResponseRedirect(reverse('exams'))
		else:
			return super(ExamUpdateView, self).post(request, *args, **kwargs)

# Exams Delete View ########################################################################
def exams_delete(request, pk):

	del_exam = Exam.objects.get(id=pk)

	if request.method == 'POST':
		if request.POST.get('delete_button') is not None:
			del_exam.delete()
			messages.success(request, u'Іспит з "%s" успішно видалено' % del_exam.subject)
			return HttpResponseRedirect(reverse('exams'))
		else:
			messages.warning(request, u'Видалення іспиту з "%s" відмінено' % del_exam.subject)
			return HttpResponseRedirect(reverse('exams'))
	else:
		return render(request, 'students/exams_confirm_delete.html', {'del_exam':del_exam})

students/views/groups.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from django.forms import ModelForm, ValidationError
from django.views.generic import UpdateView, DeleteView

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from crispy_forms.bootstrap import FormActions

from ..models.students import Student
from ..models.groups import Group

from ..util import paginate, get_current_group


# List of Groups ######################################################

def group_list(request):
	current_group = get_current_group(request)

	if current_group:
		groups = Group.objects.filter(id=current_group.id)
	else:
		groups = Group.objects.all().order_by('title')
	
	# try to order groups list
	order_by = request.GET.get('order_by', '')
	if order_by == 'title':
		groups = groups.order_by(order_by)
		if request.GET.get('reverse', '') == '1':
			groups = groups.reverse()
		
	# paginate of groups list
	context = paginate(groups, 3, request, {'groups':groups}, var_name='groups')

	return render(request, 'students/groups_list.html', context)

# Group Edit View ###########################################################
class GroupUpdateForm(ModelForm):
	class Meta:
		model = Group
		fields = ['title', 'leader', 'notes']

	def __init__(self, *args, **kwargs):
		super(GroupUpdateForm, self).__init__(*args, **kwargs)

		self.helper = FormHelper(self)

		# set form tag attributes
		self.helper.form_action = reverse('groups_edit', kwargs = {'pk': kwargs['instance'].id})
		self.helper.form_method = 'post'
		self.helper.form_class = 'form-horizontal'

		# set form field properties
		self.helper.help_text_inline = True
		self.helper.html5_required = True
		self.helper.label_class = 'col-sm-3 control-label'
		self.helper.field_class = 'col-sm-6'

		# add buttons
		self.helper.add_input(Submit('add_button', u'Зберегти', css_class="btn btn-primary"))
		self.helper.add_input(Submit('cancel_button', u'Скасувати', css_class="btn btn-link"))

	def clean_leader(self):
		students = Student.objects.filter(student_group=self.instance)
		if len(students) > 0 and self.cleaned_data['leader'] not in students:
			raise ValidationError(u'Студент не належить до цієї групи', code='invalid')
		return self.cleaned_data['leader']

class GroupUpdateView(SuccessMessageMixin, UpdateView):
	model = Group
	template_name = 'students/groups_edit.html'
	form_class = GroupUpdateForm
	success_message = u"Група %(calc_title)s успішно збережена"

	def get_success_url(self):
		return reverse('groups')

	def get_success_message(self, cleaned_data):
		return self.success_message % dict(cleaned_data, calc_title=self.object.title,)

	def post(self, request, *args, **kwargs):
		if request.POST.get('cancel_button'):
			messages.warning(request, u'Редагування групи %s скасовано!' % request.POST['title'])
			return HttpResponseRedirect(reverse('groups'))
		else:
			return super(GroupUpdateView, self).post(request, *args, **kwargs)


# Group Delete Form #########################################################
def groups_delete(request, pk):
	
	del_group = Group.objects.get(id=pk)
	studentsOfDelGroup = Student.objects.filter(student_group=del_group)

	if request.method == 'POST':
		if request.POST.get('delete_button') is not None:
			if len(studentsOfDelGroup) == 0:
				del_group.delete()
				messages.success(request, u'Групу %s успішно видалено' % del_group.title)
				return HttpResponseRedirect(reverse('groups'))
			else:
				messages.error(request, u'Групу %s неможливо видалити, бо у групі є студенти' % del_group.title)
				return HttpResponseRedirect(reverse('groups'))
		else:
			messages.warning(request, u'Видалення групи %s відмінено' % del_group.title)
			return HttpResponseRedirect(reverse('groups'))
	else:
		return render(request, 'students/groups_confirm_delete.html', {'del_group':del_group})

students/templates/students/base.html
{% load i18n %}

{% load static from staticfiles %}

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="description" value="Система обліку студентів">
		<meta viewport="content" initialscale="1">
		<title>{% trans "Students Accounting Service "%} - {% block meta_title %}{% endblock meta_title %}</title>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/bootstrap/3.3.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.0.0/css/bootstrap-datetimepicker.min.css">
		<link rel="stylesheet" href="{{PORTAL_URL}}{% static "css/main.css" %}">
		{% block extra_css %}{% endblock extra_css %}
	
	</head>
	<body>
		<div class="container wrap">
			<div class="col-xs-8">
				<h1>{% trans "Students Accounting Service" %}</h1>
			</div>

			<!--User Authentification Block -->	
			{% if user.is_authenticated %}
				<!-- User's toolbar for authenticated users-->
				<div class="col-xs-4" id="user-toolbar">
					<a href="{% url "profile" %}">{{ user.username }}: {{ user.last_name }}</a> |
					<a href="{% url "users:auth_logout" %}">{% trans "Logout" %}</a>
				</div>

			{% else %}

				<!--User's toolbar for anonymous users -->
				<div class="col-xs-4" id="user-toolbar">
					<a href="{% url "users:auth_login" %}">{% trans "Login" %}</a> |
					<a href="{% url "users:registration_register" %}">{% trans "Register" %}</a>
				</div>
			{% endif %}
			<!--End of Authentification Block-->

		<!--Navigation-->
			<div class="col-xs-12">
				<ul class="nav nav-tabs">
				{% url "home" as home	%}				
				  <li {% if request.path == home %}class="active"{% endif %}><a href="{% url "home" %}">{% trans "Students" %}</a></li>
				  {% if user.is_authenticated %}
				  	<li {% if "groups" in request.path %}class="active"{% endif %}><a href="{% url "groups" %}">{% trans "Groups" %}</a></li>
				  	<li {% if "exams" in request.path %}class="active"{% endif %}><a href="{% url "exams" %}">{% trans "Exams" %}</a></li>
				   	<li {% if "journal" in request.path %}class="active"{% endif %}><a href="{% url "journal" %}">{% trans "Journal" %}</a></li>
				  {% endif %}
				  {% if perms.auth.add_user %}
					  <li {% if "contact-admin" in request.path %}class="active"{% endif %}><a href="{% url "contact_admin" %}">{% trans "Contact" %}</a></li>
				  {% endif %}
				</ul>
			</div>
			<!--Main Content-->
			<div class="col-xs-12 content">
				
				<!-- Status Message -->
				{% block status_message %}
					{% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{% if message.tags == 'warning' %}warning{% elif message.tags == 'success' %}success{% else %}danger{% endif %}" role="alert">{{ message }}</div>
                        {% endfor %}
                	{% endif %}
				{% endblock status_message %}

				<div class="col-xs-2 title">
					<h2>{% block title %}{% endblock title %}</h2>
				</div>
				<div class="col-xs-3">
				{% if user.is_authenticated %}
					{% block add_New %}{% endblock add_New %}
				{% endif %}
				</div>
		
				<div class="col-xs-3" id="group-selector">
					<strong>{% trans "Group:" %}</strong>
					<select>
						<option value="">{% trans "All students" %}</option>
						{% for group in GROUPS %}
						<option value="{{ group.id }}"{% if group.selected %}selected="1"{% endif %}>
							{{ group.title }}{% if group.leader %}, {{ group.leader }}{% endif %}
						</option>
						{% endfor %}
					</select>
				</div>
			
		
			{% block content %}{% endblock content %}
			
			</div>
			<div class="col-xs-12 footer">
				
					{% block pagination %}{% endblock pagination %}
				<div class="col-xs-12 copyright">
					<p>&copy 2016 {% trans "Students Accounting Service" %}</p>
				</div>
			</div>
		</div>

		<!-- Modal Boiler Plate -->
		<div class="modal fade" id="myModal" tabindex="-1" role="dialog"
			aria-labelledby="myModalLabel" aria-hidden="true">
  			<div class="modal-dialog" role="document">
    			<div class="modal-content">
      				<div class="modal-header">
        				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
        					<span aria-hidden="true">&times;</span>
        				</button>
        				<h2 class="modal-title" id="myModalLabel"></h4>
        			</div>
      				<div class="modal-body"></div>
      				<div class="modal-footer"></div>
      			</div>
      		</div>
      	</div>

		<!-- JavaScript Section-->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
		.<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.51/jquery.form.min.js"></script>
		<script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.min.js"></script>
		<script src="{{PORTAL_URL}}{% static "js/jquery.cookie.js" %}"></script>
		<script src="https://cdn.jsdelivr.net/bootstrap/3.3.0/js/bootstrap.min.js"></script>
		<script src="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.0.0/
		js/bootstrap-datetimepicker.min.js"></script>
		<script src="{% url "django.views.i18n.javascript_catalog" %}"></script>
		<script src="{{PORTAL_URL}}{% static "js/main.js" %}"></script>
		{% block extra_js %}{% endblock extra_js %}
	</body>
</html>

students/templates/students/exams_add.html
{% extends 'students/base.html' %}

{% load static from staticfiles %}

{% block meta_title %}Додати Іспит{% endblock meta_title %}

{% block title %}Додати Іспит{% endblock title %}

{% block status_message %}
	{% if errors %}
		<div class="alert alert-danger">Будь-ласка виправте всі помилки</div>
	{% endif %}
{% endblock status_message %}

{% block content %}

<div class="col-xs-8 add_form">
	<form action="{% url "exams_add" %}" method="POST"
			enctype="multipart/form-data" class="form-horizontal">
			{% csrf_token %}
		<div class="form-group {% if errors.subject %}has-error{% endif %}">
			<label for='subject' class="col-sm-2 control-label">Предмет*</label>
			<div class="col-sm-10 input-form">
				<input type="text" value="{{request.POST.subject}}"
				 name="subject" id="subject"
				 placeholder="Введіть назву предмета" class="form-control" />
				 <span class="help-block">{{ errors.subject }}</span>
			 </div>
		</div>
		<div class="form-group {% if errors.dataAndTime %}has-error{% endif %}">
			<label for="dataAndTime" class="col-sm-2 control-label">Дата і час іспиту*</label>
			<div class="controls col-sm-10 input-form">
				<div class="input-group">
					<input type="text" value="{{request.POST.dataAndTime}}"
					name="dataAndTime" id="dataAndTime"
					placeholder="Напр. 2016-11-01 14:00" class="datetimeinput form-control"/>
					<span class="input-group-addon active">
						<span class="glyphicon glyphicon-calendar"></span>
					</span>
				</div>
				<span class="help-block">{{ errors.dataAndTime }}</span>
			</div>
		</div>
		<div class="form-group {% if errors.teacher %}has-error{% endif %}">
			<label for="teacher" class="col-sm-2 control-label">Викладач*</label>
			<div class="col-sm-10 input-form">
				<input type="text" value="{{request.POST.teacher}}"
				 name="teacher" id="teacher" placeholder="Введіть прізвище та ініціали викладача" class="form-control" />
				 <span class="help-block">{{ errors.teacher }}</span>
			 </div>
		</div>
		<div class="form-group {% if errors.exam_group %}has-error{% endif %}">
			<label for="exam_group" class="col-sm-2 control-label">Група*</label>
			<div class="col-sm-10 input-form">
				<select name="exam_group" id="exam_group" class="form-control">
					<option value="">Виберіть групу</option>
					{% for group in groups %}
					<option value="{{group.id}}" 
						{% if group.id == request.POST.exam_group|add:0 %}selected="1"{% endif %}>{{ group.title }}
					</option>
					{% endfor %}
				</select>
				<span class="help-block">{{ errors.exam_group }}</span>
			</div>
		</div>
		
		<div class="form-group">
			<label class="col-sm-2 control-label"></label>
			<div class="col-sm-10 input-form">
				<input type="submit" value="Додати" name="add_button" class="btn btn-primary">
				<button type="submit" name="cancel_button" class="btn btn-link">Скасувати</button>
			</div>
		</div>
	</form>
</div>

{% endblock content %}
{% block pagination %}
<div class="withoutPagination"></div>
{% endblock %}

students/templates/students/exams_confirm_delete.html
{% extends 'students/base.html' %}

{% load static from staticfiles %}

{% block meta_title %}Видалення Іспиту{% endblock meta_title %}

{% block title %}Видалення Іспиту{% endblock title %}

{% block status_message %}
	
{% endblock status_message %}

{% block content %}

<div class="col-xs-8 add_form">
	<form action="{% url "exams_delete" del_exam.id %}" method="post">
	{% csrf_token %}
	<p>Ви дійсно бажаєте видалити іспит з "{{ del_exam.subject }}"?</p> 
	<input type="submit" value="Так" name="delete_button"
			class="btn btn-danger">
	<input type="submit" value="Скасувати" name="cancel_button"
			class="btn btn-link">
	</form>
</div>

{% endblock content %}

{% block pagination %}
<div class="withoutPagination"></div>
{% endblock %}

students/templates/students/exams_edit.html
{% extends 'students/base.html' %}

{% load static from staticfiles %}
{% load crispy_forms_tags %}

{% block meta_title %}Редагувати Іспит{% endblock meta_title %}

{% block title %}Редагувати Іспит{% endblock title %}

{% block status_message %}
	{% if form.errors %}
		<div class="alert alert-danger">Будь-ласка виправте всі помилки</div>
	{% endif %}
{% endblock status_message %}

{% block content %}

<div class="col-xs-8 add_form">
	{% crispy form %}
</div>

{% endblock content %}

{% block pagination %}
<div class="withoutPagination"></div>
{% endblock %}